#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)"
source "$ROOT_DIR/sim/ns3/scripts/publication_env.sh"

derive_live_visualization_defaults "${UAVS:-100}" 0

LIVE=1 \
MOBILITY="${MOBILITY:-1}" \
NS3_NR_BS_HEIGHT="${NS3_NR_BS_HEIGHT:-35}" \
NS3_NR_DISTANCE="${NS3_NR_DISTANCE:-500}" \
NS3_NR_SCENARIO_WIDTH="${NS3_NR_SCENARIO_WIDTH:-1200}" \
NS3_NR_SCENARIO_HEIGHT="${NS3_NR_SCENARIO_HEIGHT:-1200}" \
NS3_NR_FREQUENCY="${NS3_NR_FREQUENCY:-3500000000}" \
NS3_NR_BANDWIDTH="${NS3_NR_BANDWIDTH:-40000000}" \
NS3_NR_NUMEROLOGY="${NS3_NR_NUMEROLOGY:-1}" \
NS3_NR_TX_POWER="${NS3_NR_TX_POWER:-43}" \
NS3_TELEMETRY_PAYLOAD="${NS3_TELEMETRY_PAYLOAD:-180}" \
NS3_TELEMETRY_INTERVAL_MS="${NS3_TELEMETRY_INTERVAL_MS:-100}" \
NS3_CONTROL_PAYLOAD="${NS3_CONTROL_PAYLOAD:-96}" \
NS3_CONTROL_INTERVAL_MS="${NS3_CONTROL_INTERVAL_MS:-500}" \
LIVE_INTERVAL_MS="${LIVE_INTERVAL_MS:-75}" \
"${ROOT_DIR}/sim/ns3/scripts/run_uav_nr.sh" "$@"
