#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)"
source "$ROOT_DIR/sim/ns3/scripts/publication_env.sh"

derive_live_visualization_defaults "${UAVS:-100}" 0

LIVE=1 \
MOBILITY="${MOBILITY:-1}" \
NS3_LTE_INTERSITE_DISTANCE="${NS3_LTE_INTERSITE_DISTANCE:-750}" \
NS3_LTE_COVERAGE_RADIUS="${NS3_LTE_COVERAGE_RADIUS:-250}" \
NS3_LTE_DL_BANDWIDTH="${NS3_LTE_DL_BANDWIDTH:-50}" \
NS3_LTE_UL_BANDWIDTH="${NS3_LTE_UL_BANDWIDTH:-50}" \
NS3_LTE_TX_POWER="${NS3_LTE_TX_POWER:-30}" \
NS3_TELEMETRY_PAYLOAD="${NS3_TELEMETRY_PAYLOAD:-180}" \
NS3_TELEMETRY_INTERVAL_MS="${NS3_TELEMETRY_INTERVAL_MS:-100}" \
NS3_CONTROL_PAYLOAD="${NS3_CONTROL_PAYLOAD:-96}" \
NS3_CONTROL_INTERVAL_MS="${NS3_CONTROL_INTERVAL_MS:-500}" \
LIVE_INTERVAL_MS="${LIVE_INTERVAL_MS:-75}" \
"${ROOT_DIR}/sim/ns3/scripts/run_uav_lte.sh" "$@"
