#!/usr/bin/env python3
"""Generate the LTE security-sweep campaign config (Paper 2)."""
from __future__ import annotations

import json
from pathlib import Path

CALIBRATION_FLEETS = (1, 10, 100)
HOLDOUT_FLEETS = (50,)
PROFILES = ("none", "tls", "wireguard", "openvpn")
MOTIONS = ("static", "mob")
REPS = 3

CAMPAIGN_NAME = "lte-security-sweep-v1"
DESCRIPTION = (
    "LTE security-overhead sweep for Paper 2. Profiles {none, tls, wireguard, openvpn} "
    "across fleets {1, 10, 100} (calibration) and {50} (hold-out), static and mobile, 3 reps each. "
    "All runs are simulator-only; field_run_id stays empty until matched field runs exist."
)


def family_id(fleet: int, motion: str, profile: str) -> str:
    return f"lte-{fleet}-{motion}-{profile}-secsweep"


def family_entry(fleet: int, motion: str, profile: str) -> dict:
    fid = family_id(fleet, motion, profile)
    return {
        "family_id": fid,
        "field_scenario_id": f"field-{fid.replace('-secsweep', '-secsweep')}",
        "sim_scenario_id": f"sim-{fid}",
        "notes": (
            f"{fleet}-UAV {motion} cell with {profile} security overlay. "
            "Generated by analysis/generate_lte_security_sweep_campaign.py."
        ),
    }


def build_families() -> dict[str, list[dict]]:
    cal = [
        family_entry(f, m, p)
        for f in CALIBRATION_FLEETS
        for p in PROFILES
        for m in MOTIONS
    ]
    hold = [
        family_entry(f, m, p)
        for f in HOLDOUT_FLEETS
        for p in PROFILES
        for m in MOTIONS
    ]
    return {"calibration": cal, "holdout": hold}


def build_runs(families: dict[str, list[dict]]) -> list[dict]:
    runs: list[dict] = []
    for split, fam_list in families.items():
        prefix = "cal" if split == "calibration" else "hold"
        for fam in fam_list:
            base = fam["family_id"].replace("-secsweep", "")
            for rep in range(1, REPS + 1):
                runs.append(
                    {
                        "pair_id": f"{prefix}-{base}-r{rep}",
                        "split": split,
                        "family_id": fam["family_id"],
                        "repetition": rep,
                        "field_run_id": "",
                        "sim_run_id": "",
                    }
                )
    return runs


def build_campaign() -> dict:
    families = build_families()
    runs = build_runs(families)
    return {
        "campaign_name": CAMPAIGN_NAME,
        "description": DESCRIPTION,
        "raw_root": "logs/raw",
        "normalized_root": "logs/normalized",
        "analysis_root": "logs/analysis",
        "output_root": "logs/analysis/campaigns",
        "default_readiness_profile": "dev",
        "repetitions_per_family": REPS,
        "quality_gates": {
            "require_all_expected_pairs": False,
            "require_all_holdout_pairs": False,
            "minimum_metric_overlap_per_pair": 3,
            "minimum_comparable_metric_overlap_per_pair": 0,
            "require_real_hardware_field_execution": False,
            "require_configured_field_sync": False,
            "require_sim_link_model_export": True,
        },
        "dev_quality_gates": {
            "require_all_expected_pairs": False,
            "require_all_holdout_pairs": False,
            "minimum_metric_overlap_per_pair": 1,
            "minimum_comparable_metric_overlap_per_pair": 0,
            "require_configured_field_sync": False,
            "require_real_hardware_field_execution": False,
            "require_sim_link_model_export": False,
        },
        "families": families,
        "runs": runs,
    }


def main() -> int:
    out_path = (
        Path(__file__).resolve().parent
        / "templates"
        / "lte_security_sweep_campaign.template.json"
    )
    out_path.parent.mkdir(parents=True, exist_ok=True)
    payload = build_campaign()
    out_path.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")
    print(f"wrote {out_path} ({len(payload['runs'])} runs across {len(payload['families']['calibration']) + len(payload['families']['holdout'])} families)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
